version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 99
    groups:
      ssdlc-actions:
        patterns:
          - "mozilla/ssdlc-actions/*"
    cooldown:
      default-days: 7
