name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  push:
    branches:
      - amo

permissions: {}

jobs:
  test:
    env:
      CARGO_TERM_COLOR: always
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10  # v6.0.3
        with:
          persist-credentials: false
      - name: Install Rust
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          source $HOME/.cargo/env
          rustup toolchain install
          rustup component add clippy
          rustup component add rustfmt
      - run: cargo test
      - run: cargo doc --no-deps
      - run: cargo clippy --tests --no-deps -- --deny clippy::all
      - run: cargo fmt --all --check
